---
title: Functieaanroepen activeren met de Sense HAT-joystick
hero_image: images/banner.png
description: Hoe een functieaanroep te activeren als reactie op joystickgebeurtenissen
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python, sensehat"
site_areas:
steps:
  - title: Activeer functies

