title: Triggering function calls with the Sense HAT joystick
hero_image: images/banner.png
description: How to trigger a function call in response to joystick events
original_url:
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: 
interests: 
technologies: "python, sensehat"
site_areas:
steps:
  - title: Trigger functions

