---
title: Déclencher des appels de fonction avec le joystick Sense HAT
hero_image: images/banner.png
description: Comment déclencher un appel de fonction en réponse à des événements liés au joystick
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python, sensehat"
site_areas:
steps:
  - 
    title: Fonctions de déclenchement

